return {
    'Mighty Strikes',
    'Hundred Fists',
    'Benediction',
    'Manafont',
    'Chainspell',
    'Perfect Dodge',
    'Invincible',
    'Blood Weapon',
    'Familiar',   
    'Soul Voice',
    'Eagle Eye Shot',
    'Meikyo Shisui',
    'Mijin Gakure',
    'Spirit Surge',
    'Astral Flow',
    'Azure Lore',
    'Wild Card',
    'Overdrive',
    'Trance',
    'Tabula Rasa',
}